# https://en.wikipedia.org/wiki/Enigma_rotor_details
import string

IDENTITY_MAP = string.ascii_uppercase

MAP_SET_1294_COMMERCIAL = [
    'DMTWSILRUYQNKFEJCAZBPGXOHV', 
    'HQZGPJTMOBLNCIFDYAWVEUSRKX', 
    'UQNTLSZFMREHDPXKIBVYGJCWOA'
]

MAP_SET_ENIGMA_1 = [
    'EKMFLGDQVZNTOWYHXUSPAIBRCJ',
    'AJDKSIRUXBLHWTMCQGZNPYFVOE',
    'BDFHJLCPRTXVZNYEIWGAKMUSQO'
]

REFLECTOR_A = 'EJMZALYXVBWFCRQUONTSPIKHGD'